# Count patients
#
# This query depends on metadata in mGraph:

PREFIX meta: <urn:meta#>
PREFIX mGraph: <urn:test:mGraph>

select (count(?patientId) as ?nPatients) {
select distinct ?patientId { 
  graph mGraph: { 
    ?s a meta:Graph ;
      meta:patientId ?patientId .
  } }
}

