# File:  count-patients-by-fhir-resource-type.rq
# If you make changes to this query, please check them into
# github under noflo-rdf-components/sparql/fhir
###########################################################
#
# Count patients by FHIR resource type
#
# This queries uses metadata in the mGraph: graph to
# count patient graphs by FHIR resource type.

PREFIX meta: <urn:meta#>
PREFIX mGraph: <urn:local:mGraph>

select ?fhirResourceType (count(?patientId) as ?nPatients) {
select distinct ?fhirResourceType ?patientId { 
  graph mGraph: { 
    ?g a meta:Graph ;
      meta:patientId ?patientId ;
      meta:fhirResourceType ?fhirResourceType .
  } }
}
group by ?fhirResourceType

