# Dumpt FHIR MedicationDispense triples for a patient ID.
# The patient ID is hard-coded into the "bind" statement below.
#
# This query depends on metadata in the mGraph: graph.

PREFIX meta: <urn:meta#>
PREFIX mGraph: <urn:test:mGraph>
PREFIX fhir: <http://hl7.org/fhir/>

construct { ?s ?p ?v }
where {
select distinct * { {
  select distinct ?graph { 
    bind( "1000919" as ?patientId ) .
    graph mGraph: { 
      ?graph a meta:Graph ;
        meta:patientId ?patientId ;
        meta:fhirResourceType fhir:MedicationDispense .
    } }
  }
  graph ?graph {
    ?s ?p ?v . 
  }
}
}

